### ISSUE TITLE
Switch to a different environment

### ISSUE THREAD

**Issue by mstaniak** [ModelOriented/shapper#14]
Is it possible to change r-reticulate envir to a different one?

**Comment by mstaniak** [comment]
If not, can you add it as a feature?

**Comment by maksymiuks** [comment]
Dear @mstaniak 
To change r-reticulate env to a different one you have to execute following commands:
reticulate::use_virtualenv("path_to_your_env")
or for conda
reticulate::use_conda("name_of_conda_env")
**before** attaching shapper. 

There is no painless way to add this as a feature, it would require to rebuild package and remove .onLoad function which would crash every script where shapper is included right now.

**Comment by mstaniak** [comment]
Can you please include that information in the package documentation?

**Comment by maksymiuks** [comment]
I will be introduced with next shapper realease

**Comment by mstaniak** [comment]
thanks
