### ISSUE TITLE
Duplicated `theme_drwhy*`

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/shapper#17]
Currently in the shapper we have hard copies of drwhy themes
```
> library("shapper")
Attaching package: ‘shapper’
The following objects are masked from ‘package:DALEX’:
    theme_drwhy, theme_drwhy_colors, theme_drwhy_vertical
```

maybe we can use directly themes from DALEX package?
as it is done in iBreakDown
https://github.com/ModelOriented/iBreakDown/blob/master/R/plot_break_down.R#L25

this way we will not need to maintain separate copies of theme_*

**Comment by maksymiuks** [comment]
Done, thanks :)
